[1,"\u001B[0m\u001B[1m\u001B[31merror\u001B[0m: Uncaught Error: Project _quarto.yml validation failed.\n\nIn file _quarto.yml\n(line 44, columns 3--11) property name \u001B[34mcontents\u001B[39m is invalid\n43: \u001B[34m        href: https://github.com/jtvandijk/GEOG0030\u001B[39m\n44: \u001B[34m  contents:\u001B[39m\n     ~~~~~~~~~\n45: \u001B[34m    - section: \"Module overview\"\u001B[39m\n\u001B[34mℹ\u001B[39m The error happened in location \u001B[34mwebsite\u001B[39m:\u001B[34mcontents\u001B[39m.\n\u001B[34mℹ\u001B[39m Did you mean \u001B[34mcomments\u001B[39m?\n\n\nIn file _quarto.yml\n(line 10, columns 1--9) Field \"\u001B[34mbook\u001B[39m\" has value \u001B[34m# output\u001B[39m, which must instead be an object\n10: \u001B[34m# output\u001B[39m\n   ~~~~~~~~~\n11: \u001B[34mformat:\u001B[39m\n\u001B[31m✖\u001B[39m The value \u001B[34m# output\u001B[39m is of type a null value.\n\u001B[34mℹ\u001B[39m The error happened in location \u001B[34mbook\u001B[39m.\n\n        throw new ValidationError2(errorMessage, yamlValidationErrors);\n\u001B[0m\u001B[31m              ^\u001B[0m\n    at \u001B[0m\u001B[1m\u001B[3mreadAndValidateYamlFromFile\u001B[0m (\u001B[0m\u001B[36mfile:///Applications/quarto/bin/quarto.js\u001B[0m:\u001B[0m\u001B[33m42120\u001B[0m:\u001B[0m\u001B[33m15\u001B[0m)\n    at async \u001B[0m\u001B[36mfile:///Applications/quarto/bin/quarto.js\u001B[0m:\u001B[0m\u001B[33m82873\u001B[0m:\u001B[0m\u001B[33m26\u001B[0m\n    at async \u001B[0m\u001B[1m\u001B[3mprojectContext\u001B[0m (\u001B[0m\u001B[36mfile:///Applications/quarto/bin/quarto.js\u001B[0m:\u001B[0m\u001B[33m82725\u001B[0m:\u001B[0m\u001B[33m26\u001B[0m)\n    at async \u001B[0m\u001B[1m\u001B[3mrender\u001B[0m (\u001B[0m\u001B[36mfile:///Applications/quarto/bin/quarto.js\u001B[0m:\u001B[0m\u001B[33m90657\u001B[0m:\u001B[0m\u001B[33m21\u001B[0m)\n"]
